# Generated by Django 3.2.12 on 2022-04-16 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('oils', 'Oils'), ('filters', 'Filters'), ('commercial_items', 'Commercial Items'), ('equipment_spares', 'Equipment Spares'), ('misc', 'Miscellaneous')], max_length=50)),
                ('item_name', models.CharField(max_length=256)),
                ('identification_num', models.CharField(max_length=20)),
                ('mfr_part_num', models.CharField(max_length=20)),
                ('min_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_level', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_of_measure', models.CharField(choices=[('number', 'Number'), ('litre', 'Litres'), ('kg', 'Kg')], max_length=10)),
                ('stock_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('needs_to_be_replenished', models.BooleanField(default=False, editable=False)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockReplenishmentLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_replenishment', models.DateTimeField(auto_now_add=True)),
                ('quantity_added', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='replenishment_log_entries', to='store.stockitem')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='replenished_by_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StockIssuanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issuance', models.DateTimeField(auto_now_add=True)),
                ('quantity_issued', models.DecimalField(decimal_places=2, max_digits=10)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issued_by_logs', to=settings.AUTH_USER_MODEL)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issued_to_logs', to=settings.AUTH_USER_MODEL)),
                ('stock_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='issuance_log_entries', to='store.stockitem')),
            ],
        ),
    ]
